version:"3.8"


services:
    postgres:
        image: postgres:15
        container_name: postgres_db
        environment:
            POSTGRES_USER: lama
            POSTGRES_PASSWORD: lama123456
            POSTGRES_DB: school
        ports:
            - "5413:5432"
        volumes:
            -postgres_data:/var/lib/postgresql/data
    

    app:
        container_name: nextjs_app
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgresql://lama:lama123456@localhost:5413/school
            depends_on:
                - postgres

